///*
// * Main.java
// *
// * Created on __DATE__, __TIME__
// */
//
//package com.wch.codetools.cdxthis;
//
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.io.File;
//
//import javax.swing.JFileChooser;
//import javax.swing.UIManager;
//import javax.swing.UnsupportedLookAndFeelException;
//
///**
// * 
// * @author __USER__
// */
//public class Main extends javax.swing.JFrame implements ActionListener {
//
//	/** Creates new form Main */
//	public Main() {
//		initComponents();
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//	// GEN-BEGIN:initComponents
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">
//	private void initComponents() {
//
//		jProgressBar1 = new javax.swing.JProgressBar();
//		buttonGroup1 = new javax.swing.ButtonGroup();
//		jRadioButton1 = new javax.swing.JRadioButton();
//		jRadioButton2 = new javax.swing.JRadioButton();
//		jButton1 = new javax.swing.JButton();
//		jButton2 = new javax.swing.JButton();
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//		setTitle("\u540e\u53f0\u751f\u6210");
//
//		buttonGroup1.add(jRadioButton1);
//		jRadioButton1.setText("\u751f\u6210dao\u5c42");
//
//		buttonGroup1.add(jRadioButton2);
//		jRadioButton2.setText("\u751f\u6210service\u5c42");
//
//		jButton1.setText("\u53d6     \u6d88");
//
//		jButton2.setText("\u5f00    \u59cb");
//
//		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
//				getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(layout
//				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//				.add(layout.createSequentialGroup().add(47, 47, 47)
//						.add(jRadioButton1).add(18, 18, 18).add(jRadioButton2)
//						.addContainerGap(112, Short.MAX_VALUE))
//				.add(org.jdesktop.layout.GroupLayout.TRAILING,
//						layout.createSequentialGroup()
//								.addContainerGap(183, Short.MAX_VALUE)
//								.add(jButton2).add(18, 18, 18).add(jButton1)
//								.addContainerGap()));
//		layout.setVerticalGroup(layout
//				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//				.add(layout
//						.createSequentialGroup()
//						.addContainerGap()
//						.add(layout
//								.createParallelGroup(
//										org.jdesktop.layout.GroupLayout.BASELINE)
//								.add(jRadioButton1).add(jRadioButton2))
//						.add(30, 30, 30)
//						.add(layout
//								.createParallelGroup(
//										org.jdesktop.layout.GroupLayout.BASELINE,
//										false).add(jButton1).add(jButton2))
//						.addContainerGap()));
//
//		pack();
//	}// </editor-fold>
//		// GEN-END:initComponents
//
//	/**
//	 * @param args
//	 *            the command line arguments
//	 */
//	public static void main(String args[]) {
//		try {
//			UIManager
//					.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
//		} catch (ClassNotFoundException e) {
//			e.printStackTrace();
//		} catch (InstantiationException e) {
//			e.printStackTrace();
//		} catch (IllegalAccessException e) {
//			e.printStackTrace();
//		} catch (UnsupportedLookAndFeelException e) {
//			e.printStackTrace();
//		}
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new Main().setVisible(true);
//			}
//		});
//	}
//
//	// GEN-BEGIN:variables
//	// Variables declaration - do not modify
//	private javax.swing.ButtonGroup buttonGroup1;
//	private javax.swing.JButton jButton1;
//	private javax.swing.JButton jButton2;
//	private javax.swing.JProgressBar jProgressBar1;
//	private javax.swing.JRadioButton jRadioButton1;
//	private javax.swing.JRadioButton jRadioButton2;
//
//	// End of variables declaration//GEN-END:variables
//	/**
//	 * @Title: actionPerformed
//	 * @Description: TODO文(这里用一句话描述这个方法的作用)
//	 * @最后修改人：文川豪
//	 * @最后修改时间：2011-12-30 下午03:33:48
//	 * @see java.awt.event.ActionListener#actionPerformed(java.awt.event.ActionEvent)
//	 * @param e
//	 *            对方法的参数进行描述
//	 */
//	public void actionPerformed(ActionEvent e) {
//		File curfile = new File(
//				"E:\\myeclipse\\workspace\\cdxtHisService\\src\\com\\cdxt\\entity");
//		JFileChooser chooser = new JFileChooser(curfile);
//		int i = chooser.showOpenDialog(this);
//		if (i == 0) {
//			File file = chooser.getSelectedFile();
//			if (file == null) {
//				this.dispose();
//			} else {
//				CdxtHisCode cdxtHisCode = new CdxtHisCode();
//				try {
//					cdxtHisCode.explorService(file);
//				} catch (Exception e1) {
//					e1.printStackTrace();
//				}
//			}
//			this.dispose();
//		}
//
//	}
//
//}